services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=sbdocs'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
    volumes:
      - pgvector_data_gpt:/var/lib/postgresql/data

volumes:
  pgvector_data_gpt:
    driver: local